#!/usr/bin/env python3
import time
import os
import logging
from src import cudamon
from src import init

if __name__ == '__main__':
    try:
        init.initialize_logger()
        logging.info('Starting CUDAMon')
        cudamon = cudamon.CUDAMon()
        while True:
            cudamon.check_gpus()
            time.sleep(int(os.getenv('POLL_SEC', 60)))
    except Exception as e:
        logging.critical('Unhandled exception:', exc_info=True)
        raise
    