#!/usr/bin/env python3
import time
import os
from src import cudamon

if __name__ == '__main__':
    print('Starting CUDAMon')
    while True:
        cudamon = cudamon.CUDAMon()
        cudamon.check_gpu()
        time.sleep(int(os.getenv('POLL_SEC', 60)))
    